networks:
  invisionu-ats-network:
    external: true

volumes:
  go-mod-cache: {}
  go-build-cache: {}

services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: invisionu_ats_backend_dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["-config=local"]
    volumes:
      - ./config:/app/config:ro
    networks:
      - invisionu-ats-network

  golang-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: invisionu_ats_backend_test
    working_dir: /src
    env_file:
      - .env
    volumes:
      - .:/src
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: ["sh"]
    networks:
      - invisionu-ats-network
