-- +goose Up
-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    phone_number VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auth_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose VARCHAR(64) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_codes_user_purpose ON auth_codes(user_id, purpose, created_at DESC);

CREATE TABLE IF NOT EXISTS refresh_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    user_agent TEXT,
    ip_address VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_refresh_sessions_user_id ON refresh_sessions(user_id);

CREATE TABLE IF NOT EXISTS programs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(64) NOT NULL,
    code VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS application_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    uploaded_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    application_id UUID,
    file_type VARCHAR(64) NOT NULL,
    bucket_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    etag VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    program_id INTEGER NOT NULL REFERENCES programs(id),
    review_stage VARCHAR(64) NOT NULL,
    decision VARCHAR(64) NOT NULL,
    video_file_id UUID NOT NULL REFERENCES application_files(id),
    video_audio_file_id UUID REFERENCES application_files(id),
    video_transcript TEXT,
    screening_error TEXT,
    submitted_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE application_files
    ADD CONSTRAINT fk_application_files_application
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_applications_user_id ON applications(user_id);
CREATE INDEX IF NOT EXISTS idx_applications_program_id ON applications(program_id);
CREATE INDEX IF NOT EXISTS idx_applications_review_stage ON applications(review_stage);
CREATE INDEX IF NOT EXISTS idx_applications_decision ON applications(decision);

CREATE TABLE IF NOT EXISTS personality_tests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(128) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS personality_test_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id UUID NOT NULL REFERENCES personality_tests(id) ON DELETE CASCADE,
    question_order INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_personality_test_questions_order
    ON personality_test_questions(test_id, question_order);

CREATE TABLE IF NOT EXISTS personality_test_options (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id UUID NOT NULL REFERENCES personality_test_questions(id) ON DELETE CASCADE,
    option_order INTEGER NOT NULL,
    option_key VARCHAR(8) NOT NULL,
    option_text TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_personality_test_options_order
    ON personality_test_options(question_id, option_order);

CREATE TABLE IF NOT EXISTS application_test_answers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    question_id UUID NOT NULL REFERENCES personality_test_questions(id) ON DELETE CASCADE,
    option_id UUID NOT NULL REFERENCES personality_test_options(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_application_test_answers_unique
    ON application_test_answers(application_id, question_id);

CREATE TABLE IF NOT EXISTS scoring_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    model_name VARCHAR(255) NOT NULL,
    result_json JSONB NOT NULL,
    recommendation VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scoring_runs_application_id_created_at
    ON scoring_runs(application_id, created_at DESC);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS scoring_runs;
DROP TABLE IF EXISTS application_test_answers;
DROP TABLE IF EXISTS personality_test_options;
DROP TABLE IF EXISTS personality_test_questions;
DROP TABLE IF EXISTS personality_tests;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS application_files;
DROP TABLE IF EXISTS programs;
DROP TABLE IF EXISTS refresh_sessions;
DROP TABLE IF EXISTS auth_codes;
DROP TABLE IF EXISTS users;
-- +goose StatementEnd
